In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import csv

In [17]:
covid_data_file1 = '../data/covid_race_data_tracker.csv'
covid_tracker_df = pd.read_csv(covid_data_file1, dtype="object", encoding="utf-8")
covid_tracker_df.head()

,Date,State,Cases_Total,Cases_White,Cases_Black,Cases_LatinX,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Deaths_LatinX,Deaths_Asian,Deaths_AIAN,Deaths_NHPI,Deaths_Multiracial,Deaths_Other,Deaths_Unknown,Deaths_Ethnicity_Hispanic,Deaths_Ethnicity_NonHispanic,Deaths_Ethnicity_Unknown
0,20200722,AK,2132,750,49,NaN,67,282,76,61,...,NaN,2,4,1,0,0,1,0,18,1
1,20200722,AL,71813,22694,20884,NaN,267,NaN,NaN,NaN,...,NaN,4,NaN,NaN,NaN,27,100,45,1126,193
2,20200722,AR,35246,17406,7521,NaN,498,101,1985,NaN,...,NaN,6,0,30,NaN,27,3,41,336,3
3,20200722,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20200722,AZ,150609,24130,3246,34645,1096,9085,NaN,NaN,...,786,32,394,NaN,NaN,53,495,786,1693,495

In [18]:
covid_tracker_df.columns

Index(['Date', 'State', 'Cases_Total', 'Cases_White', 'Cases_Black',
       'Cases_LatinX', 'Cases_Asian', 'Cases_AIAN', 'Cases_NHPI',
       'Cases_Multiracial', 'Cases_Other', 'Cases_Unknown',
       'Cases_Ethnicity_Hispanic', 'Cases_Ethnicity_NonHispanic',
       'Cases_Ethnicity_Unknown', 'Deaths_Total', 'Deaths_White',
       'Deaths_Black', 'Deaths_LatinX', 'Deaths_Asian', 'Deaths_AIAN',
       'Deaths_NHPI', 'Deaths_Multiracial', 'Deaths_Other', 'Deaths_Unknown',
       'Deaths_Ethnicity_Hispanic', 'Deaths_Ethnicity_NonHispanic',
       'Deaths_Ethnicity_Unknown'],
      dtype='object')

In [19]:
type(covid_tracker_df['Cases_Total'][0])

str

In [33]:
# Check for 'NaN' and if true, replace them with value 0
check_for_nan = covid_tracker_df['Cases_Total'].isnull().values.any()
print (check_for_nan)

False

In [21]:
covid_tracker_df['Cases_Total'] = covid_tracker_df['Cases_Total'].fillna(0)
covid_tracker_df['Cases_White'] = covid_tracker_df['Cases_White'].fillna(0)
covid_tracker_df['Cases_Black'] = covid_tracker_df['Cases_Black'].fillna(0)
covid_tracker_df['Cases_LatinX'] = covid_tracker_df['Cases_LatinX'].fillna(0)
covid_tracker_df['Cases_Asian'] = covid_tracker_df['Cases_Asian'].fillna(0)
covid_tracker_df['Cases_AIAN'] = covid_tracker_df['Cases_AIAN'].fillna(0)
covid_tracker_df['Cases_NHPI'] = covid_tracker_df['Cases_NHPI'].fillna(0)
covid_tracker_df['Cases_Multiracial'] = covid_tracker_df['Cases_Multiracial'].fillna(0)
covid_tracker_df['Cases_Other'] = covid_tracker_df['Cases_Other'].fillna(0)
covid_tracker_df['Cases_Unknown'] = covid_tracker_df['Cases_Unknown'].fillna(0)
covid_tracker_df['Cases_Ethnicity_Hispanic'] = covid_tracker_df['Cases_Ethnicity_Hispanic'].fillna(0)
covid_tracker_df['Cases_Ethnicity_NonHispanic'] = covid_tracker_df['Cases_Ethnicity_NonHispanic'].fillna(0)
covid_tracker_df['Cases_Ethnicity_Unknown'] = covid_tracker_df['Cases_Ethnicity_Unknown'].fillna(0)
covid_tracker_df['Deaths_Total'] = covid_tracker_df['Deaths_Total'].fillna(0)
covid_tracker_df['Deaths_White'] = covid_tracker_df['Deaths_White'].fillna(0)
covid_tracker_df['Deaths_Black'] = covid_tracker_df['Deaths_Black'].fillna(0)
covid_tracker_df['Deaths_LatinX'] = covid_tracker_df['Deaths_LatinX'].fillna(0)
covid_tracker_df['Deaths_Asian'] = covid_tracker_df['Deaths_Asian'].fillna(0)
covid_tracker_df['Deaths_AIAN'] = covid_tracker_df['Deaths_AIAN'].fillna(0)
covid_tracker_df['Deaths_NHPI'] = covid_tracker_df['Deaths_NHPI'].fillna(0)
covid_tracker_df['Deaths_Multiracial'] = covid_tracker_df['Deaths_Multiracial'].fillna(0)
covid_tracker_df['Deaths_Other'] = covid_tracker_df['Deaths_Other'].fillna(0)
covid_tracker_df['Deaths_Unknown'] = covid_tracker_df['Deaths_Unknown'].fillna(0)
covid_tracker_df['Deaths_Ethnicity_Hispanic'] = covid_tracker_df['Deaths_Ethnicity_Hispanic'].fillna(0)
covid_tracker_df['Deaths_Ethnicity_NonHispanic'] = covid_tracker_df['Deaths_Ethnicity_NonHispanic'].fillna(0)
covid_tracker_df['Deaths_Ethnicity_Unknown'] = covid_tracker_df['Deaths_Ethnicity_Unknown'].fillna(0)

In [22]:
check_for_nan = covid_tracker_df.isnull().values.any()
print (check_for_nan)

False

In [23]:
covid_tracker_df.head()

,Date,State,Cases_Total,Cases_White,Cases_Black,Cases_LatinX,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Deaths_LatinX,Deaths_Asian,Deaths_AIAN,Deaths_NHPI,Deaths_Multiracial,Deaths_Other,Deaths_Unknown,Deaths_Ethnicity_Hispanic,Deaths_Ethnicity_NonHispanic,Deaths_Ethnicity_Unknown
0,20200722,AK,2132,750,49,0,67,282,76,61,...,0,2,4,1,0,0,1,0,18,1
1,20200722,AL,71813,22694,20884,0,267,0,0,0,...,0,4,0,0,0,27,100,45,1126,193
2,20200722,AR,35246,17406,7521,0,498,101,1985,0,...,0,6,0,30,0,27,3,41,336,3
3,20200722,AS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20200722,AZ,150609,24130,3246,34645,1096,9085,0,0,...,786,32,394,0,0,53,495,786,1693,495

In [24]:
type(covid_tracker_df['Cases_Total'][0])

str

In [25]:
covid_tracker_df['Cases_Total']=covid_tracker_df['Cases_Total'].astype(int)
covid_tracker_df['Cases_White'] = covid_tracker_df['Cases_White'].astype(int)
covid_tracker_df['Cases_Black'] = covid_tracker_df['Cases_Black'].astype(int)
covid_tracker_df['Cases_LatinX'] = covid_tracker_df['Cases_LatinX'].astype(int)
covid_tracker_df['Cases_Asian'] = covid_tracker_df['Cases_Asian'].astype(int)
covid_tracker_df['Cases_AIAN'] = covid_tracker_df['Cases_AIAN'].astype(int)
covid_tracker_df['Cases_NHPI'] = covid_tracker_df['Cases_NHPI'].astype(int)
covid_tracker_df['Cases_Multiracial'] = covid_tracker_df['Cases_Multiracial'].astype(int)
covid_tracker_df['Cases_Other'] = covid_tracker_df['Cases_Other'].astype(int)
covid_tracker_df['Cases_Unknown'] = covid_tracker_df['Cases_Unknown'].astype(int)
covid_tracker_df['Cases_Ethnicity_Hispanic'] = covid_tracker_df['Cases_Ethnicity_Hispanic'].astype(int)
covid_tracker_df['Cases_Ethnicity_NonHispanic'] = covid_tracker_df['Cases_Ethnicity_NonHispanic'].astype(int)
covid_tracker_df['Cases_Ethnicity_Unknown'] = covid_tracker_df['Cases_Ethnicity_Unknown'].astype(int)
covid_tracker_df['Deaths_Total'] = covid_tracker_df['Deaths_Total'].astype(int)
covid_tracker_df['Deaths_White'] = covid_tracker_df['Deaths_White'].astype(int)
covid_tracker_df['Deaths_Black'] = covid_tracker_df['Deaths_Black'].astype(int)
covid_tracker_df['Deaths_LatinX'] = covid_tracker_df['Deaths_LatinX'].astype(int)
covid_tracker_df['Deaths_Asian'] = covid_tracker_df['Deaths_Asian'].astype(int)
covid_tracker_df['Deaths_AIAN'] = covid_tracker_df['Deaths_AIAN'].astype(int)
covid_tracker_df['Deaths_NHPI'] = covid_tracker_df['Deaths_NHPI'].astype(int)
covid_tracker_df['Deaths_Multiracial'] = covid_tracker_df['Deaths_Multiracial'].astype(int)
covid_tracker_df['Deaths_Other'] = covid_tracker_df['Deaths_Other'].astype(int)
covid_tracker_df['Deaths_Unknown'] = covid_tracker_df['Deaths_Unknown'].astype(int)
covid_tracker_df['Deaths_Ethnicity_Hispanic'] = covid_tracker_df['Deaths_Ethnicity_Hispanic'].astype(int)
covid_tracker_df['Deaths_Ethnicity_NonHispanic'] = covid_tracker_df['Deaths_Ethnicity_NonHispanic'].astype(int)
covid_tracker_df['Deaths_Ethnicity_Unknown'] = covid_tracker_df['Deaths_Ethnicity_Unknown'].astype(int)

In [26]:
type(covid_tracker_df['Cases_Total'][0])

numpy.int64

In [27]:
# Export the clean covid tracker data into a csv
covid_tracker_df.to_csv("../data/race_data_tracker.csv",encoding='utf-8', index=False)